title: Noor Abdullah Adiana
url: http://localhost:4000/

owner:
    name: Noor Abdullah Adiana
    mail: nooradiana@gmail.com
    twitter: noorAddianna
    facebook: noorAddianna
    github: NoorAdiana
    google_plus: +NoorAdiana
    disqus_shortname: nooradiana

paginate:   3
markdown:   rdiscount
permalink:  /post/:title
pygments:   true
timezone:   Asia/Jakarta